language: ruby
rvm:
  - ruby-2.3.3
branches:
  only:
    - "master"
env:
  global:
    -
      LC_ALL=en_US.UTF_8
      LANG=en_US.UTF_8
matrix:
  fast_finish: true
  include:
    - rvm: jruby-9.1.5.0
      env: DISABLE_NOKOGIRI=1
    - rvm: ruby-2.4.1
      env: DISABLE_V8=1
  allow_failures:
    - rvm: jruby-9.1.5.0
      env: DISABLE_NOKOGIRI=1
    - rvm: jruby-9.1.5.0
script:
  - bundle exec rake test_ci
  - bundle exec appraisal install && FOCUS=rouge bundle exec appraisal rake spec
cache: bundler
sudo: false
git:
  depth: 10
